[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./charity-api"
restartPolicyType = "always"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100

[[deploy.env]]
name = "PORT"
value = "8080"

[[deploy.env]]
name = "GIN_MODE"
value = "release"
